### ISSUE TITLE
如何使用全局共享计时的一个按钮？

### ISSUE THREAD

**Issue by 694120752** [zhwayne/WLButtonCountingDownDemo#1]
请问 一处开始倒计时 别的按钮同时开始倒计时如何实现？
试着使用了相同的id  不能成功。

**Comment by zhwayne** [comment]
可以尝试配合 `NSNotificationCenter` 实现。若依旧不能，能否提供你的代码？

**Comment by 694120752** [comment]
可以说的具体点吗 ，如何配合NSNotificationCenter呢
这是我的创建方法：
`   WLCaptcheButton* btn = [WLCaptcheButton new];
            btn.disabledBackgroundColor = [UIColor clearColor];
            btn.disabledTitleColor = [UIColor grayColor];
            btn.identifyKey = @"1";
            self.authCodeBtn = btn;
            [btn setTitle:@"获取验证码" forState:UIControlStateNormal];
            [btn setTitleColor:[UIColor grayColor] forState:UIControlStateNormal];
            [btn addTarget:self action:@selector(getCode) forControlEvents:UIControlEventTouchUpInside];
            [image addSubview:btn];
            btn.sd_layout
            .topSpaceToView(image, 7)
            .bottomSpaceToView(image, 7)
            .rightSpaceToView(image, 10)
            .leftSpaceToView(text, 0);`
getCode的事件为获取验证码 成功后回调 触发fire， 我应该怎样获取到其他identifyKey的按钮并触发他们呢

**Comment by 694120752** [comment]
好的 我知道了
感谢

**Comment by 694120752** [comment]
如果这个页面还不存在 通知无法收到呀

**Comment by zhwayne** [comment]
😄那这样吧，你把所有 `Button` 的 `identifyKey` 设置为唯一字符串，并且在 `ViewController` 的 `viewWillAppear:` 方法中调用 `Button` 的 `setNeedsLayout` 和 `layoutIfNeeded `即可，省去了用通知的麻烦：

```
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    
    [self.buttons makeObjectsPerformSelector:@selector(setNeedsLayout)];
    [self.buttons makeObjectsPerformSelector:@selector(layoutIfNeeded)];
}
```

**Comment by 694120752** [comment]
太感谢了 
已解决
